sgx demo initial remote attestation
enarx-archive/demo pull request #13
Opened 2019-08-17 18:30 UTC by lkatalin

I probably want to make some more changes, ex. pass the certs by command line arg instead of including the files, but just so you have this to look at ASAP.

2019-08-18 12:38 UTC, npmccallum requested changes
I put some initial comments in the individual files that should help with readability for the next round of reviews. Unfortunately, there's also a major problem with the structure. We currently have three parties:
1. the tenant (run on the client)
2. the attested enclave (run on the host)
3. the daemon which communicates with the tenant (run on the host)

Unfortunately, the daemon currently validates the certificate chain. However, this is the job of the tenant.

The job of the daemon is to get the measurement of the enclave (the quote) and return the quote and any additional data needed for validation to the tenant. It is the tenant who gathers all the information from the daemon and then performs validation. So the code will have to be reworked.

I have some other comments for the next round of review. But I'd like to solve the readability and structural problems first.

2019-08-18 12:38 UTC, npmccallum commented on intel-sgx/Cargo.toml
> +authors = ["LKatalin"]
Full name and email please.

2019-08-18 12:38 UTC, npmccallum commented on intel-sgx/attestation-daemon/Cargo.toml
> +authors = ["LKatalin"]
Full name and email please.

2019-08-18 12:38 UTC, npmccallum commented on intel-sgx/attestation-enclave/Cargo.toml
> +authors = ["LKatalin"]
Full name and email please.

2019-08-18 12:38 UTC, npmccallum commented on intel-sgx/attestation-enclave/src/main.rs
> +        match stream {
Don't use match here (or in other files either). This is just a demo. Let's `unwrap()` it for readability.

2019-08-18 12:38 UTC, npmccallum commented on intel-sgx/attestation-enclave/src/main.rs
> +}
Don't use micro functions like this (fix other places too). It hurts readability. If a function is less than a handful of lines, just do it inline. I'd much rather see:

```rust
// Other code ...

// Create report
let report = Report::for_target(&t, &[0; 64]);

// Other code ...
```

2019-08-19 15:38 UTC, lkatalin commented on intel-sgx/Cargo.toml
> +authors = ["LKatalin"]
Done.

2019-08-19 15:38 UTC, lkatalin commented on intel-sgx/attestation-daemon/Cargo.toml
> +authors = ["LKatalin"]
Done.

2019-08-19 15:38 UTC, lkatalin commented on intel-sgx/attestation-enclave/Cargo.toml
> +authors = ["LKatalin"]
Done.

2019-08-19 15:40 UTC, lkatalin commented on intel-sgx/attestation-enclave/src/main.rs
> +        match stream {
I removed all the matches and now have unwrap() or sometimes expect() in case error messages seemed useful.

2019-08-19 15:41 UTC, lkatalin commented on intel-sgx/attestation-enclave/src/main.rs
> +}
Got it, I put these short lines of code back in main() for all the files. For the tenant's verification of the Quote, I still broke it down into individual functions because to me that seemed more clear, but let me know.

2019-08-19 15:47 UTC, lkatalin commented
@npmccallum Please take a look at the changes when you get a chance. Thanks for pointing out that the tenant needs to do verification; I strongly agree. I initially meant to do it that way but was blocked by something (now I don't recall what that was and it doesn't matter because I fixed it). My current next step is also to get the cert chain loaded in a more intelligent way.

2019-09-05 13:59 UTC, npmccallum requested changes
Can you please squash these commits into a logical series of commits? This probably means a single commit as this is a new demo. We don't want to merge stream of consciousness.

2019-09-05 15:56 UTC, npmccallum submitted a review, later dismissed
1. Comments need to be complete sentences with proper grammar and punctuation.

2. Is there a reason the enclave can't just send the report to dcap directly and then forward the completed quote to the daemon?

3. We really should avoid shipping raw structs over the wire. Can the `Quote` type be used with Serde for serialization?

4. The same is true for parsing inside the tenant. We really don't want to be doing byte-level parsing. There should be pre-defined data types that use serialization (see my comment about Serde above).

5. OpenSSL (and mbedtls) should have functions for the type conversions you're doing. Please confirm.

6. It is unclear to me that `verify_chain_sigs()` actually does signature validation. At least that's not how I'm used to doing signature validation. Traditionally, I've built up a full certificate chain and called a single verify function on the whole chain. For example, if Intel decided to add multiple intermediate certificates this could would have to be re-written.

7. Right now the tenant code is just a huge pile of functions. I'd prefer if there was discrete data types.

2019-09-05 15:56 UTC, npmccallum commented on intel-sgx/Cargo.toml
> +authors = ["LKatalin"]
I don't think this is fixed.

2019-09-05 15:56 UTC, npmccallum commented on README.md
> +5. Run the `attestation-tenant` with `cargo run <filepath>`, where filepath is the path to the PCK certificate chain from Step 3.
Please wrap the `README.md` at 80 columns. Thanks!

2019-09-05 15:56 UTC, npmccallum commented on intel-sgx/Cargo.toml
> +dcap-ql = "0.2.0"
What is the purpose of these dependencies? This top-level directory should just be an empty workspace.

2019-09-05 15:56 UTC, npmccallum commented on intel-sgx/attestation-daemon/src/main.rs
> +extern crate dcap_ql;
`extern crate CRATE;` is no longer necessary in stable. Please remove it.

2019-09-05 15:56 UTC, npmccallum commented on intel-sgx/attestation-daemon/src/main.rs
> +        let mut enclave_cnx = TcpStream::connect("localhost:1032").unwrap();
This is just a comment. No action is required. It is really gross that we have to hard-code the address and port here. In the future, the SGX enclave management daemon (probably named `enarx-sgx`) should spawn the enclaves directly. Is it possible to pass a `socketpair()` to the enclave for management communication? We should probably discuss this at some point.

2019-09-05 15:56 UTC, npmccallum commented on intel-sgx/attestation-daemon/src/main.rs
> +        stream_client.write(&quote).unwrap();
I understand what each of these chunks of code does. But I don't understand *why* this code works like this. Could you add additional information to the comments explaining this? Also, be sure that comments are complete sentences with proper grammar and punctuation.

2019-09-05 15:56 UTC, npmccallum commented on intel-sgx/attestation-enclave/Cargo.toml
> +sgx-isa = { version = "0.3.1", features = ["sgxstd"] }
Please document what this feature does and why you turn it on.

2019-09-05 15:56 UTC, npmccallum commented on intel-sgx/src/main.rs
> +fn main() {}
This file should be unnecessary.

2019-09-05 15:57 UTC, npmccallum commented
Also, I merged @mbestavros's PR, so now there is a conflict. Please resolve it.

2019-09-22 13:20 UTC, lkatalin commented on intel-sgx/src/main.rs
> +fn main() {}
I removed this.

2019-09-22 13:20 UTC, lkatalin commented on intel-sgx/attestation-enclave/Cargo.toml
> +sgx-isa = { version = "0.3.1", features = ["sgxstd"] }
Done.

2019-09-22 13:27 UTC, lkatalin commented on intel-sgx/attestation-daemon/src/main.rs
> +        stream_client.write(&quote).unwrap();
Yes, that's a good point, and I added additional comments to each part of the code to explain its purpose (ex. that the Targetinfo is needed to generate the Report). But please let me know if anything is still unclear.

2019-09-22 13:28 UTC, lkatalin commented on intel-sgx/attestation-daemon/src/main.rs
> +        let mut enclave_cnx = TcpStream::connect("localhost:1032").unwrap();
I'd be happy to discuss this and create this in a cleaner way. I can open an issue for it, also.

2019-09-22 13:28 UTC, lkatalin commented on intel-sgx/attestation-daemon/src/main.rs
> +extern crate dcap_ql;
Done.

2019-09-22 13:28 UTC, lkatalin commented on intel-sgx/Cargo.toml
> +dcap-ql = "0.2.0"
I've removed these from the top level.

2019-09-22 13:29 UTC, lkatalin commented on README.md
> +5. Run the `attestation-tenant` with `cargo run <filepath>`, where filepath is the path to the PCK certificate chain from Step 3.
I wrapped it at 80 columns. It may be a little too short now; please let me know if so.

2019-09-22 13:50 UTC, lkatalin commented
> 1. Comments need to be complete sentences with proper grammar and punctuation.
I've added full-sentence comments that are more descriptive. Please let me know if any are still unclear!

> 2. Is there a reason the enclave can't just send the report to dcap directly and then forward the completed quote to the daemon?
Yes, the reason is that currently the `dcap-ql` crate can't be used in an enclave. We will need to write our own `enclave-runner` to add this functionality. I could open an issue for this as well.

> 3. We really should avoid shipping raw structs over the wire. Can the `Quote` type be used with Serde for serialization?
I've added Serde support for the Quote, Targetinfo, and Report types in a [PR to Fortanix](https://github.com/fortanix/rust-sgx/pull/177). Currently the Targetinfo and Report types are serialized into strings with `serde_json` and then sent as bytes. If this doesn't make sense, I will do it a different way. `serde_json` also has a `vec` type, but it requires a JSON map. The Quote was and still is sent over the wire as a `Vec<u8>`, not as a struct, so that is not serialized.

> 4. The same is true for parsing inside the tenant. We really don't want to be doing byte-level parsing. There should be pre-defined data types that use serialization (see my comment about Serde above).
I also opened a [PR to Fortanix](https://github.com/fortanix/rust-sgx/pull/173) to have support for Quote-related types for PCK cert chain-based attestation, and currently the `attestation-tenant` makes use of these. 

> 5. OpenSSL (and mbedtls) should have functions for the type conversions you're doing. Please confirm.
I've removed the manual conversions (to ASN.1, for example) and am using the OpenSSL versions now.

> 6. It is unclear to me that `verify_chain_sigs()` actually does signature validation. At least that's not how I'm used to doing signature validation. Traditionally, I've built up a full certificate chain and called a single verify function on the whole chain. For example, if Intel decided to add multiple intermediate certificates this could would have to be re-written.
I've changed this to build up the entire chain and then verify only the leaf PCK cert in the context of the chain. Hopefully this is what you meant.

> 7. Right now the tenant code is just a huge pile of functions. I'd prefer if there was discrete data types.
I grouped the functions together and came up with `chain`, `key`, and `sig` types that each have their own file and are imported as modules. These types have the old functions as methods.

Other thoughts:

- In addition to the separate PRs submitted to Fortanix for `serde` and `PCK cert chain`-related struct support, I created a [third branch](https://github.com/lkatalin/rust-sgx/tree/serde-pck) of my `rust-sgx` fork, which merges both of these functionalities. Currently the `intel-sgx` `Cargo.toml` depends on this third branch of the `rust-sgx` fork. When both PRs are merged to Fortanix, the dependency can point to Fortanix's repo.

- I don't like the way the size of the buffers receiving the serialized structs is hardcoded right now, as it's messy and pretty brittle. I can open an issue to change this too, but I need to look into a better way to do this.

2019-10-10 11:17 UTC, steveej reviewed
I took a first very uninformed pass on this. We'll likely have at least one more, if I manage to gain some understanding on the business logic.

2019-10-10 11:17 UTC, steveej commented on intel-sgx/Cargo.toml
> +dcap-ql = { git = "https://github.com/lkatalin/rust-sgx", branch = "serde-pck" }
for the sake of being able to reproduce your exact state you need to do either of two things, or both:
* change this line to include a specific revision by adding `, rev = "your-git-rev-here"`
* commit the `Cargo.lock`

2019-10-10 11:17 UTC, steveej commented on intel-sgx/Cargo.toml
> +sgx-isa = { git = "https://github.com/lkatalin/rust-sgx", branch = "serde-pck"}
for the sake of being able to reproduce your exact state you need to do either of two things, or both:
* change this line to include a specific revision by adding `, rev = "your-git-rev-here"`
* commit the `Cargo.lock`

2019-10-10 11:17 UTC, steveej commented on intel-sgx/attestation-daemon/src/main.rs
> +        // The attestation daemon retrieves the Quoting Enclave's Target Info and
First of likely very ignorant questions on the business  logic here :-)

Is the Target Info retrieved from the CPU?

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-daemon/src/main.rs
> +        let report: sgx_isa::Report = serde_json::from_str(&serialized_report).unwrap();
I think you could use a conjunction of https://doc.rust-lang.org/std/io/trait.Read.html#method.take and https://docs.serde.rs/serde_json/de/fn.from_reader.html to skip the buffer and the string conversion altogether.

2019-10-10 11:17 UTC, steveeJ commented on README.md
> +A demonstration of remote attestation for an SGX enclave.
Maybe you could elaborate a bit here, giving a high-level description for the demo flow.

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/key.rs
> +        assert!(ec_key.check_key().is_ok());
I find it surprising to see an assertion here. Could you instead return a `Result<Self>`, remove this line and use `?` in the previous line instead of unwrapping? The same may be true for all other unwraps and assertions in this file. Then again, I'm not sure serious this code is so feel free to ignore my comment completely.

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/key.rs
> +    pub fn new_from_xy(xy_coords: &[u8]) -> Self {
I'd expect a `///` style comment on top of any `pub` keyword

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/key.rs
> +pub struct Key {
I'd expect a `///` style comment on top of any `pub` keyword

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/key.rs
> +    pub fn new_from_pubkey(pkey: PKey<Public>) -> Self {
I'd expect a `///` style comment on top of any `pub` keyword

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/key.rs
> +    pub fn verify_sig(&self, signed: &[u8], sig: &Vec<u8>) -> () {
I'd expect a `///` style comment on top of any `pub` keyword

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/key.rs
> +    // This verifies the SHA-256 hash of the Attestation Public Key || QEAuthData
Please turn this comment into a `///` prefixed one. Thanks for describing what happens here. I'm curious to learn about the cryptography from these comments.

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/cert_chain.rs
> +        assert!(context
maybe return a `Result<()>` instead the assertion here. see similar comments on other files

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/main.rs
> +const VEC_QUOTE_SIZE: usize = 4702;
that's an untypical number. do you mind sharing how this size is determined, e.g. with a reference?

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/main.rs
> +// 1. That the Quote's PCK Certificate (embedded in the Cert Data) is valid.
Maybe you could refer to the spec which describes _PCK_ and other acronyms somewhere in the top of this file?

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/main.rs
> +fn main() {
Personally I would probably refactor this main and extract some functions with descriptive names, but feel free to ignore this suggestion.

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/sig.rs
> +pub struct Signature {
missing `///`on a `pub`

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/sig.rs
> +    pub fn to_der_vec(self) -> Vec<u8> {
missing `///`on a `pub`

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/cert_chain.rs
> +    pub fn new_from_chain(c: Vec<X509>, leaf: &X509) -> Self {
missing `///` on `pub`

2019-10-10 11:17 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/cert_chain.rs
> +    pub fn set_max_len(&mut self, len: usize) -> () {
missing `///` on `pub`, and many more down in this file ;-)

2019-10-10 15:24 UTC, lkatalin commented on intel-sgx/attestation-tenant/src/sig.rs
> +pub struct Signature {
What do you mean by this one? I don't think I'm familiar.

2019-10-10 16:09 UTC, lkatalin commented on intel-sgx/attestation-daemon/src/main.rs
> +        // The attestation daemon retrieves the Quoting Enclave's Target Info and
Yes, I believe so. In the Fortanix code it comes from [here](https://github.com/fortanix/rust-sgx/blob/master/dcap-ql-sys/src/lib.rs#L76), but I haven't been able to find enough detail on how Intel's `sgx_qe_get_target_info` works. I'll look into it further.

2019-10-10 17:16 UTC, lkatalin commented on intel-sgx/Cargo.toml
> +dcap-ql = { git = "https://github.com/lkatalin/rust-sgx", branch = "serde-pck" }
This is good to know! Thanks.

2019-10-10 20:21 UTC, lkatalin commented on intel-sgx/attestation-daemon/src/main.rs
> +        let report: sgx_isa::Report = serde_json::from_str(&serialized_report).unwrap();
I made this change in this file, but I don't see a way to do it in `attestation-enclave/src/main.rs` because `from_reader(stream)` consumes my stream, and I need to write to that same stream later. Any thoughts?

2019-10-10 21:18 UTC, lkatalin commented on intel-sgx/attestation-tenant/src/main.rs
> +fn main() {
I would like to get @npmccallum 's input before I do that, as earlier I had refactored to have more code in main rather than extracted functions which were very short.

2019-10-11 16:51 UTC, lkatalin commented on intel-sgx/attestation-tenant/src/main.rs
> +const VEC_QUOTE_SIZE: usize = 4702;
Looks like I don't need to use this size at all, thankfully.

2019-10-11 16:51 UTC, lkatalin commented on intel-sgx/attestation-tenant/src/main.rs
> +// 1. That the Quote's PCK Certificate (embedded in the Cert Data) is valid.
I added two links to the top of the file. However, there isn't any very good, concise, and up to date documentation that I can find... hoping to put something together in the near future.

2019-10-11 19:23 UTC, lkatalin commented
@steveeJ I think I've addressed all of your comments - let me know what you think, when you get a chance. Thanks.

2019-10-16 09:51 UTC, steveej reviewed
I took another pass. I'd like to sync on the TODOs in the code as I need some more explanation in order to be helpful with them ;-)

2019-10-16 09:51 UTC, steveeJ commented on intel-sgx/attestation-enclave/src/main.rs
> +const SER_TARGETINFO_SIZE: usize = 196; // TODO: Hope to not use this.
What does this TODO mean?

2019-10-16 09:51 UTC, steveeJ commented on intel-sgx/attestation-enclave/src/main.rs
> +        stream.read_exact(&mut buf)?;
Regarding the comment above it would be possible to read to `EOF`, if the stream provides that. In any case we'd probably still want an upper limit to not hang endlessly.

2019-10-16 09:51 UTC, steveej commented on intel-sgx/attestation-tenant/src/key.rs
> +            panic!("Hash of attestation key is not valid.")
Maybe throwing an error would be enough here?

Otherwise if you really do want to panic, you can replace the `if .. { panic ..}` construct with a single `assert`. as in `assert!(hash == hashed_data, "Hash of attestation key is not valid")`

2019-10-16 09:51 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/main.rs
> +        .expect("You must supply the path of a valid PCK certificate chain as the first argument.");
I think this check should be moved to the beginning of the program to be able to fail early.

2019-10-17 17:57 UTC, lkatalin commented on intel-sgx/attestation-enclave/src/main.rs
> +        stream.read_exact(&mut buf)?;
Let me know if you find a way to do this, thanks.

2019-10-17 17:58 UTC, lkatalin commented on intel-sgx/attestation-tenant/src/key.rs
> +            panic!("Hash of attestation key is not valid.")
I changed this to a custom `HashError`.

2019-10-17 17:58 UTC, lkatalin commented on intel-sgx/attestation-tenant/src/main.rs
> +        .expect("You must supply the path of a valid PCK certificate chain as the first argument.");
Done.

2019-10-17 18:02 UTC, lkatalin commented
@steveeJ I fixed the error handling in `attestation-tenant/key.rs` and moved the argument check to the beginning of `attestation-tenant/main.rs`.

2019-10-18 12:32 UTC, steveeJ commented on intel-sgx/attestation-enclave/src/main.rs
> +const SER_TARGETINFO_SIZE: usize = 196; // TODO: Hope to not use this.
As discussed out-of-band, this number has been found through a manual process of computing the struct's size. Hardcoding this number is potentially brittle. An option would be to pass the stream to serde directly via its `from_reader` method. However @lkatalin expressed an issue with that, as it consumes then stream and can't be written to later on.

2019-10-24 20:49 UTC, steveeJ commented on intel-sgx/attestation-enclave/src/main.rs
> +}
I like to use inline scopes for separating functionality out without creating an actual function. That works nicely with scopes which just return one value.

2019-10-24 20:50 UTC, steveeJ commented on intel-sgx/attestation-tenant/src/main.rs
> +fn main() {
Yep, I saw we have different opinions here. My isn't very strong though, and I suggest to use scopes as a compromise in the future.

2019-10-24 20:51 UTC, steveeJ commented on intel-sgx/attestation-enclave/src/main.rs
> +const SER_TARGETINFO_SIZE: usize = 196; // TODO: Hope to not use this.
This is fixed now.

2019-10-24 20:51 UTC, steveeJ commented on intel-sgx/attestation-enclave/src/main.rs
> +        stream.read_exact(&mut buf)?;
I found a way, as you already know :wink:

2019-10-24 20:52 UTC, steveej approved these changes
From what I could tell all of @npmccallum's comments are addressed, and so are mine.

Thanks for this first SGX demo @lkatalin :tada:

2019-10-24 20:55 UTC, steveeJ commented
@lkatalin would you mind just quickly confirming that the following comments by @npmccallum are addressed, before I merge this?

> * OpenSSL (and mbedtls) should have functions for the type conversions you're doing. Please confirm.
> 
> * It is unclear to me that `verify_chain_sigs()` actually does signature validation. At least that's not how I'm used to doing signature validation. Traditionally, I've built up a full certificate chain and called a single verify function on the whole chain. For example, if Intel decided to add multiple intermediate certificates this could would have to be re-written.

2019-10-24 20:58 UTC, lkatalin commented
Yes, I used to have lots of manual functions converting from DER to ASN.1 and things like that, because I didn't realize OpenSSL had such functionality. Those were all addressed.

I also had a different function for verifying the chain that checked each intermediate cert in the chain. There is also a function for this where I can just check the leaf cert, which is what's used instead now in `cert_chain.rs`. It loops through the chain, so a changing number of intermediate certs won't break it. 

So, these were both addressed.

2019-10-24 21:02 UTC, merged