Add demo to run Rust natively in a WASM VM
enarx-archive/demo pull request #17
Opened 2019-09-02 18:36 UTC by steveeJ

2019-09-03 14:13 UTC, mbestavros reviewed
Looks good to me -- I don't notice significant changes from what you showed us offline last Friday, and we took a pretty deep dive into what everything does and why it needs to be there at that point.

If I were to nitpick, a few inline comments to explain what exactly `main.rs` is doing would be helpful for people looking at this code later.

2019-09-03 14:39 UTC, steveeJ commented
Thanks @mbestavros, I added a few comments and also changed the variable names to be more descriptive.

2019-09-03 14:50 UTC, mbestavros commented
Thanks -- definitely more immediately understandable now.

I'll defer to Nathaniel for final merge approval, but this looks good to me as-is.

2019-09-05 14:11 UTC, npmccallum requested changes
This overall looks very good to me. I've requested at least one minor change and some documentation of the `wasmtime-embed` situation.

2019-09-05 14:11 UTC, npmccallum commented on wasmtime-native-embed/src/main.rs
> +    pub struct PrintingCalc {}
I think idiomatically we want to use a unit struct here. So: `pub struct PrintingCalc();`.

2019-09-05 14:11 UTC, npmccallum commented on wasmtime-native-embed/src/main.rs
> +use app::{PrintingCalc, Calc};
Nit pick: this is probably over-verbose unless you're trying to restrict line length. `app::PrintingCalc` is very readable.

2019-09-05 14:11 UTC, npmccallum commented on wasmtime-native-embed/src/main.rs
> +    let printing_calc = PrintingCalc {};
I don't mind long variable names. But I think Rust idiomatically prefers short ones. Does Rust give any official guidance on this? For example: is `pcalc` or `printing_calc` preferred? I'm honestly not sure. But it would be good to know.

2019-09-05 14:11 UTC, npmccallum commented on wasmtime-native-embed/Cargo.toml
> +wasmtime-embed-macro = { git = "https://github.com/yurydelendik/wasmtime-embed", package = "wasmtime-embed-macro", rev = "cc5740f" }
Since we are obviously using a git repo based dependency, it would be good to explain why. It would also be good to explain what the path is towards making this a standard `crates.io` dependency is.

2019-09-05 17:22 UTC, steveeJ commented on wasmtime-native-embed/src/main.rs
> +use app::{PrintingCalc, Calc};
Do you suggest to split this into two separate lines?

2019-09-05 17:24 UTC, npmccallum commented on wasmtime-native-embed/src/main.rs
> +use app::{PrintingCalc, Calc};
No. I mean remove the `use` statement altogether.

I generally try to balance my use of namespace importing with concerns like readability, line length, etc. If you think this is worthwhile, then maybe move it within the `main()` function?

2019-09-05 17:27 UTC, steveeJ commented on wasmtime-native-embed/src/main.rs
> +    let printing_calc = PrintingCalc {};
I find long variable names very helpful and generally use them. Of course it is not the length which is significant, but the variable name as an indicator of what it's used for, in the style of the [Hungarian Notation](https://en.wikipedia.org/wiki/Hungarian_notation).

I haven't looked at any guidelines for this but I find the short variables names found in the C ecosystem extremely confusing, which usually puts a barrier between me and a project I'd like to possibly contribute.

2019-09-05 17:28 UTC, steveeJ commented on wasmtime-native-embed/Cargo.toml
> +wasmtime-embed-macro = { git = "https://github.com/yurydelendik/wasmtime-embed", package = "wasmtime-embed-macro", rev = "cc5740f" }
I haven't thought about this much. I don't expect that specific project to ever make a release, as the macros, or a variation thereof, will likely be integrated with wasmtime-api or a different wasmtime subcrate at one point.

2019-09-05 17:41 UTC, npmccallum commented on wasmtime-native-embed/src/main.rs
> +    let printing_calc = PrintingCalc {};
I don't have a strong opinion here. (Except I detest embedding the type of a variable in its name...) But I would like to have an Enarx policy. I'm not requesting any change on this PR. I just want us to start a conversation.

2019-09-05 17:42 UTC, npmccallum commented on wasmtime-native-embed/Cargo.toml
> +wasmtime-embed-macro = { git = "https://github.com/yurydelendik/wasmtime-embed", package = "wasmtime-embed-macro", rev = "cc5740f" }
Just an inline comment saying basically the above would be fine.

2019-09-05 17:45 UTC, mbestavros commented on wasmtime-native-embed/src/main.rs
> +    let printing_calc = PrintingCalc {};
I agree with Stefan; I'm personally in favor of descriptive (-enough) variable names. Abbreviations can make things hard to parse.

2019-09-05 19:19 UTC, steveeJ commented on wasmtime-native-embed/src/main.rs
> +    let printing_calc = PrintingCalc {};
I very rarely embed the type in it the variable name. An exception might be if the scope is just doing conversion between types and I don't want or can't declare it as a type in the language itself, although I do prefer the latter.
I usually give a functional description of what the variable is used for. 

I think the Hungarian Notation is a good fit which we could set as a baseline with the explicit deviation of not including the type in the name, unless it's the main logic of the scope.

2019-09-13 14:44 UTC, steveeJ commented
@npmccallum thanks for the review. I acted on all comments except for the naming convention one. That should go in the top-level contribution guidelines.

2019-09-13 15:06 UTC, npmccallum requested changes

2019-09-13 15:06 UTC, npmccallum commented on wasmtime-native-embed/src/main.rs
> +    pub struct PrintingCalc();
I'm really sorry. I totally told you the wrong thing before. For a unit struct, the idiom is `pub struct PrintincCalc;`.

2019-09-13 15:06 UTC, npmccallum commented on wasmtime-native-embed/src/main.rs
> +    let printing_calc = PrintingCalc {};
```rust
let printing_calc = PrintingCalc {};
```

I'm really surprised that still compiles... Regardless, it needs to be updated to:

```rust
let printing_calc = PrintingCalc;
```

2019-09-13 15:26 UTC, steveeJ commented on wasmtime-native-embed/src/main.rs
> +    pub struct PrintingCalc();
no worries at all

2019-09-13 15:51 UTC, npmccallum approved these changes

2019-09-13 15:51 UTC, merged