Add Travis config to run rustfmt test
enarx-archive/demo pull request #22
Opened 2019-09-11 15:44 UTC by mbestavros

To enforce proper formatting standards on Enarx projects, we'd like to run cargo fmt on all incoming pull requests to Enarx projects. This enables the appropriate test using Travis CI.

Resolves #11.

2019-09-13 13:15 UTC, mbestavros commented
I've amended the tests to also run in the `amd-sev` subdirectory. That crate isn't properly formatted yet, which is why tests are failing. I can roll the formatting into this patch, or make a separate one if preferred.

2019-09-17 16:24 UTC, npmccallum commented
One pull request with two commits please.

2019-09-17 17:39 UTC, npmccallum commented
I can't believe I missed the obvious solution to all this. Make the parent directory a Cargo workspace.

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

2019-09-17 17:52 UTC, mbestavros commented
Agreed, that is the cleanest way to get what we need. How should I approach making that change? Separate commit adding the workspace before adding `travis.yml`?

2019-09-17 18:02 UTC, npmccallum commented
Yup. Logical commits.

2019-09-30 12:56 UTC, steveeJ commented on wasmtime-basic/src/main.rs
> +#[cfg(all(feature = "benchmark", test))]
This change seems unrelated to this PR.

2019-09-30 12:56 UTC, steveeJ commented on Cargo.toml
> +]
Please also add the `wasmtime-native-embed` crate. I think we could also use `*` to add all projects in this repo as members.

2019-09-30 12:57 UTC, steveeJ commented on .gitignore
> +Cargo.lock
Is there a reason why you don't want to commit `Cargo.lock`? I think we should rather add it to the repository.

2019-09-30 18:45 UTC, mbestavros commented on wasmtime-basic/src/main.rs
> +#[cfg(all(feature = "benchmark", test))]
Previously, the demo wouldn't run on stable (a problem introduced with [the performance benchmarking PR](https://github.com/enarx/demo/commit/84fed8564e7edab12ce4a8e4c4a13ae85a1b7165)). I thought it was resolved with that PR, but apparently not. This was causing the Travis tests to fail. This is the fix, and things now work properly.

2019-09-30 18:55 UTC, mbestavros commented on Cargo.toml
> +]
Done in the latest revision.

2019-09-30 19:03 UTC, mbestavros commented on .gitignore
> +Cargo.lock
All of Enarx's other Rust crates gitignore `Cargo.lock`, so that was the standard I used to begin with.

Looking into it a bit, I found official Rust documentation [here](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) that we'll probably want to follow. I suppose it comes down to whether we consider demos as end-user binaries or as libraries. Perhaps something of an open question -- @npmccallum, any thoughts?

2019-09-30 19:11 UTC, mbestavros commented
@npmccallum This is now rebased on @steveeJ's now-merged demo, with some additional fixes. Ready for a look.

2019-09-30 19:16 UTC, npmccallum commented on .gitignore
> +Cargo.lock
Demos are binaries.

2019-09-30 19:30 UTC, mbestavros commented on .gitignore
> +Cargo.lock
In that case, I'll amend `.gitignore`. :slightly_smiling_face:

2019-10-07 14:24 UTC, mbestavros commented
@npmccallum @steveeJ I've amended the new Travis config in this PR to include a cargo-audit test, and fixed a change being in the wrong commit. Ready for re-review.

2019-10-07 15:11 UTC, steveeJ commented
Looks like cargo audit is already revealing vulnerable dependencies for us. I suggest to bump them in a separate PR and rebase this one.

2019-10-07 15:18 UTC, mbestavros commented
@steveeJ I noticed that. It seemed like it was a broken dependency in a Wasmtime crate, so I don't know if we can bump that ourselves.

Regardless, I've removed the `audit` check and will add it back in once this is merged.

2019-10-07 15:34 UTC, steveej requested changes
The content looks good to go for now. 
The commit message are to meta for my test. Suggestions/Examples:

* "Format crate with cargofmt" --> "amd-sev: apply cargofmt"
* " Make amd-sev demo compile" --> see comment I've added as I'm not sure why the change is made
* "Fix wasmtime-basic demo to compile/run tests on stable" --> "wasmtime-basic/tests: add 'benchmark' feature-gate"

When looking at the commits one-by-one, the content of them aren't consistent with their messages. I suggest you to please go through the exercise of resetting the branch and carefully commit the changes by their logical meaning.

2019-10-07 15:34 UTC, steveeJ commented on .travis.yml
> +  - cargo generate-lockfile
Did you think about adding the workspace's `Cargo.lock` instead? Would there be any downside to that?

2019-10-07 15:34 UTC, steveeJ commented on amd-sev/src/main.rs
> +            } => panic!(),
What error is this fixing? The panic message doesn't contain any information about why it's happening.

2019-10-07 15:46 UTC, mbestavros commented on .travis.yml
> +  - cargo generate-lockfile
`Cargo.lock` is actually included now after we discussed demos being binaries above, so I suppose this line was redundant.

Regardless, it's removed now, since we're pushing `cargo-audit` down the line.

2019-10-07 15:56 UTC, mbestavros commented on amd-sev/src/main.rs
> +            } => panic!(),
Running tests on the `amd-sev` demo didn't work. When `main.rs` runs, it should return a `Reason` if it fails. A function somewhere was complaining this bit of code didn't have a specific response for `Reason::Mmio`, so this is just an empty response that satisfies that requirement and makes the test compile.

I'll try to capture that as best I can in a short commit message.

2019-10-07 16:47 UTC, steveeJ commented on amd-sev/src/main.rs
> +            } => panic!(),
The compiler error was likely something alike "non-exhaustive match pattern: Reason::Mmio" not covered. The two choices you have in such a case is to either insert the generic case which matches all remainder variants, or to cover the remainders explicitly. You chose the latter, in which case I think you should include this specific knowledge in the the panic message. If you had chosen the former, you could've given the debug representation of whatever the remainder is. I don't have an opinion on which we choose here, but I'd encourage you to go a bit beyond this mere satisfaction of the compiler.

2019-10-07 18:20 UTC, mbestavros commented on amd-sev/src/main.rs
> +            } => panic!(),
Yes, that was the error.

This makes a lot of sense, and I agree there should be some rationale for it inline. I've added a basic explanation in.

2019-10-07 18:24 UTC, mbestavros commented
@steveeJ I've reworded most of the commits; they should match up with the logical changes in each of them better now.

2019-10-07 20:00 UTC, steveej requested changes

2019-10-07 20:00 UTC, steveeJ commented on .travis.yml
> +  - rustup target add wasm32-unknown-unknown
This line doesn't fit with the commit message

2019-10-07 20:00 UTC, steveeJ commented on amd-sev/src/main.rs
> +            } => panic!("Reason::Mmio is unused here; however, the compiler will complain of a non-exhaustive match if it isn't covered. This is an empty response to prevent that error."),
That's entertaining :smiley:

How about printing the generic case and printing its debug representation instead?

```suggestion
            reason => panic!("Unexpected reason: {:?}", reason),
```

(the suggestion won't work literally)

2019-10-08 13:29 UTC, mbestavros commented on .travis.yml
> +  - rustup target add wasm32-unknown-unknown
Moved to a better commit in the latest push.

2019-10-08 14:45 UTC, mbestavros commented on amd-sev/src/main.rs
> +            } => panic!("Reason::Mmio is unused here; however, the compiler will complain of a non-exhaustive match if it isn't covered. This is an empty response to prevent that error."),
Added in latest revision.

2019-10-08 16:54 UTC, steveej submitted a review, later dismissed
This looks good to me now, thank you!

2019-10-08 17:10 UTC, steveej reviewed
I'm having second thoughts on my previous approval, specifically because the generated lockfile has to generalize the dependencies isn't guaranteed to be consistent with all of the member crate lockfiles, or I don't understand the consistency here ;-) The issue I'm seeing is that the generated lockfile can bump dependencies which are used in tests from the root of the workspace, which are different from the one inside the members.

2019-10-09 12:08 UTC, steveej requested changes
I have made change to the `ketuvim` (https://github.com/enarx/ketuvim/pull/8) so that it re-exports the `sev` crate. This alleviates the following issue, which arises when pinning `sev` in `ketuvim` to a different version than it's using internally:

```rust
error[E0308]: mismatched types
   --> amd-sev/src/main.rs:131:19
    |
131 |     launch.inject(secret, addr, len).unwrap();
    |                   ^^^^^^ expected struct `sev::launch::Secret`, found a different struct `sev::launch::Secret`
    |
    = note: expected type `sev::launch::Secret` (struct `sev::launch::Secret`)
               found type `sev::launch::Secret` (struct `sev::launch::Secret`)
note: Perhaps two different versions of crate `sev` are being used?
   --> amd-sev/src/main.rs:131:19
    |
131 |     launch.inject(secret, addr, len).unwrap();
```

2019-10-09 12:08 UTC, steveeJ commented on .travis.yml
> +  - cargo test --locked
I think we want `--frozen --locked --offline`.

2019-10-10 10:34 UTC, steveej requested changes

2019-10-10 10:34 UTC, steveeJ commented on amd-sev/Cargo.toml
> +ketuvim = { git = "https://github.com/enarx/ketuvim", rev = "062012f4e07476c7b2f303203dea12af77a53299" }
This commit can be dropped, as it reverts back to a previous ketuvim revision which is counter-effective.

2019-10-10 10:34 UTC, steveeJ commented on Cargo.lock
> +# This file is automatically @generated by Cargo.
This file needs updating. After dropping f996d30d6b7d06913f811a0eca3cc7be1ba5f4bf please run `cargo build --all` to refresh the lockfile. I suggest squashing the changes to into 37d60cf81472798549cb6905c66a08bca5bf11f5.

2019-10-10 13:21 UTC, mbestavros commented on amd-sev/Cargo.toml
> +ketuvim = { git = "https://github.com/enarx/ketuvim", rev = "062012f4e07476c7b2f303203dea12af77a53299" }
Complete absent-mindedness on my part, apologies. It's dropped in the latest revision.

2019-10-10 13:21 UTC, mbestavros commented on Cargo.lock
> +# This file is automatically @generated by Cargo.
Done in latest revision.

2019-10-10 13:44 UTC, steveeJ commented on amd-sev/Cargo.toml
> +ketuvim = { git = "https://github.com/enarx/ketuvim", rev = "062012f4e07476c7b2f303203dea12af77a53299" }
No worries at all, and no need to apologize. There's a reason why we gate contributions on pull-requests and their reviews, and it's not specific to you ;-)

2019-10-10 14:01 UTC, steveej requested changes
I think this is the last one on the issue of reproducibility. After that we'll get to what `cargo audit` has to tell us.

2019-10-10 14:01 UTC, steveej commented on .travis.yml
> +  - cargo test --all --frozen --locked --offline
Looking at the errors on Travis I realize that we do not want, or rather can't have, `--frozen` and `offline`, as they both (obviously for the latter, not so obvious for the former), restrict network access. Since we don't have the cargo cache available on Travis which lives in `~/.cargo`, the operation fails.

Apologies for the fuss :smile:

```suggestion
  - cargo test --all --locked
```

2019-10-10 14:26 UTC, steveej approved these changes
Thanks for sticking through this! :-)

2019-10-10 14:26 UTC, merged