Implement a basic Wasmtime demo
enarx-archive/demo pull request #9
Opened 2019-08-09 19:18 UTC by mbestavros

This PR implements a simple demo of Wasmtime and how Enarx may use it.

The demo builds a basic WASM binary from either Rust or C source (selectable at compile time via a Cargo feature), loads it into Wasmtime, and runs it.

This work resolves both #3 and #7. Further WASM demo work will likely build on top of this base.

2019-08-09 20:06 UTC, npmccallum commented
@mbestavros Don't forget that our policy is to squash into logical commits before submitting the PR.

2019-08-09 20:12 UTC, mbestavros commented
@npmccallum Right, apologies. Done.

2019-08-09 20:23 UTC, npmccallum requested changes
1. Run this code through `rustfmt`. A simple `cargo fmt` should do.

2. I think the abstractions (`handle_module()` and so on...) aren't holding their weight for this demo. I'd really like to see just the bare wasmtime API in a single `main()` function.

3. We probably need to turn on optimization before benchmarks. For clang: `-O3`. For rustc: `-C opt-level=3`.

2019-08-09 20:23 UTC, npmccallum commented on wasmtime-basic/Cargo.toml
> +rust = []
Need a newline at the end of the file.

2019-08-09 20:23 UTC, npmccallum commented on wasmtime-basic/README.md
> +Before you begin, you'll need to install `lld`. On Fedora, this can be accomplished with `sudo dnf install lld`.
I think this is only required by the `c` demo. Maybe we should default to the `rust` demo?

2019-08-12 17:41 UTC, mbestavros commented
@npmccallum Addressed your points. `main.rs` is significantly refactored (and shorter) as a result.

Ready for re-review.

2019-08-12 19:00 UTC, npmccallum requested changes
Getting really close!

2019-08-12 19:00 UTC, npmccallum commented on wasmtime-basic/build.rs
> +            .arg("opt-level=3")
Does this work? I think you might need another `-C`.

2019-08-12 19:00 UTC, npmccallum commented on wasmtime-basic/src/main.rs
> +    context.name_instance("wasi_unstable".to_string(), wasi);
We shouldn't actually need WASI for this demo. I think this code can be removed.

2019-08-12 19:00 UTC, npmccallum commented on wasmtime-basic/src/main.rs
> +    let input_values = &[RuntimeValue::I32 { 0: 5 }, RuntimeValue::I32 { 0: 7 }];
I don't think we need the `function_string` and `function` temporary values. Just use literals for these.

Also, use: `RuntimeValue::I32(5)` and `RuntimeValue::I32(7)`.

2019-08-12 19:00 UTC, npmccallum commented on wasmtime-basic/src/main.rs
> +    let mut instance = context.instantiate_module(None, &binary).unwrap();
Can you ask upstream if there is a good reason this doesn't take the `Read` trait here? It seems unnecessary to read the whole module into memory and then pass it in as an array. But maybe I'm wrong...

2019-08-12 19:37 UTC, mbestavros commented on wasmtime-basic/build.rs
> +            .arg("opt-level=3")
It does compile and run correctly. I don't know how to tell if it's actually optimized, though.

2019-08-12 19:47 UTC, mbestavros commented on wasmtime-basic/src/main.rs
> +    let input_values = &[RuntimeValue::I32 { 0: 5 }, RuntimeValue::I32 { 0: 7 }];
I originally used the string variables to print out the function it was running, but it is probably cleaner to do it inline.

2019-08-12 20:27 UTC, mbestavros commented on wasmtime-basic/src/main.rs
> +    let mut instance = context.instantiate_module(None, &binary).unwrap();
II'll file an issue over on the Wasmtime repo, see if they have anything to say.

2019-08-12 20:42 UTC, mbestavros commented on wasmtime-basic/src/main.rs
> +    let mut instance = context.instantiate_module(None, &binary).unwrap();
@npmccallum FYi: https://github.com/CraneStation/wasmtime/issues/272

2019-08-13 18:39 UTC, npmccallum requested changes

2019-08-13 18:39 UTC, npmccallum commented on wasmtime-basic/src/main.rs
> +        .unwrap()
One more change. Sorry!

Let's break this up. It is hard to read.

```rust
let args = [RuntimeValue::I32(5), RuntimeValue::I32(7)];
let result = context.invoke(&mut instance, &String::from("add"), &args);
match result.unwrap() {
  // ...
}
```

Also, let's find out why `invoke()` takes a `&String` rather than a `&str`.

2019-08-13 18:45 UTC, mbestavros commented on wasmtime-basic/src/main.rs
> +        .unwrap()
Turns out it does take `&str`. Weird, I distinctly recall it not accepting that before...

2019-08-13 18:55 UTC, npmccallum approved these changes

2019-08-13 18:55 UTC, merged